config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#  get '/operatings', to: 'operatings#show'
#  get '/operatings/edit', to: 'operatings#edit'
#  post '/operatings', to: 'operatings#create'

  resources :operatings
  resources :spreadsheets
 # get '/spreadsheet/:id' to: 'spreadsheet'


#  get '/projects', to: 'projects#show'
  resources :projects
  get '/projects/:id/replace', to: 'projects#replace'
  post '/projects/replace_all', to: 'projects#replace_all'

  get '/sample', to: 'operatings#sample'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operating.rb
class Operating < ApplicationRecord
	belongs_to :user
	belongs_to :project

	validates :time, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
	validates :name,		presence: true


	def begin_date
		if self.begin_year.nil? || self.begin_month.nil? then
			nil
		else
			Date.new(self.begin_year, self.begin_month, 1)
		end
	end

	def begin_date=(value)
		if value.present? then
			date = "#{value}-01".to_date
			self.begin_year = date.year
			self.begin_month = date.month
		else
			self.begin_year = nil
			self.begin_month = nil
		end
	end

	def end_date
		if self.end_year.nil? || self.end_month.nil? then
			nil
		else
			Date.new(self.end_year, self.end_month, 1)
		end
	end

	def end_date=(value)
		if value.present? then
			date = "#{value}-01".to_date
			self.end_year = date.year
			self.end_month = date.month
		else
			self.end_year = nil
			self.end_month = nil
		end
	end


	def period
		period = ""
		return if self.begin_year.nil? 
		if (self.begin_year == self.end_year) then
			period = year_to_s(self.begin_year) + ' ' + month_to_s(self.begin_month) + '〜'
			period += month_to_s(self.end_month) unless self.end_month.nil?
		else
			period = date_to_s(self.begin_year, self.begin_month) + ' 〜 '
			period += date_to_s(self.end_year, self.end_month) unless self.end_year.nil?
		end
		return period
	end

	private

	def date_to_s year, month
		year_to_s(year) + month_to_s(month)
	end

	def year_to_s year
		return " 年" if year.nil?
		"%d年" % year
	end

	def month_to_s month
		return " 月" if month.nil?
		"%d月" % month
	end


end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :role

	def group_and_name
		self.group + '／' + self.name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def get_date_param
  	if params.include?(:year) && params.include?(:month) then
		year = params[:year].to_i
		month = params[:month].to_i
		return Date.new(year, month, 1)
	else
		return Date.today
	end
  end
end

app/controllers/operatings_controller.rb
class OperatingsController < ApplicationController

	def show

		@user = User.find(params[:id])
		@users = User.all
		@date = get_date_param

		@operatings = Operating.where(user_id: @user.id, year: @date.year, month: @date.month).order(:day, :num)
		@projects = Project.all.order(:order)
	end

	def edit
		@user = User.find(params[:id])
		@date = get_date_param

		@operatings = Operating.where(user_id: @user.id, year: @date.year, month: @date.month).order(:day, :num)
		@projects = Project.all.order(:order)
	end

	def update
		user_id = params[:id]
		Operating.transaction do

			Operating.where(user_id: user_id).where(year: params[:year]).where(month: params[:month]).delete_all
			
			params[:operating].each do |i, operatings_per_day|
				num = 0
				operatings_per_day.each do |j, operating|
					@operating = Operating.new(operating_params(operating))
					next if @operating.project_id.nil?
					@operating.user_id = user_id
					@operating.num = num
					@operating.save!
					num += 1
				end
			end
		end
		redirect_to action: :show
		rescue ActiveRecord::RecordInvalid => invalid
		render plain: invalid.record.errors.full_messages
		rescue => e
		render plain: e.message
	end

	private

	def operating_params parameter
		parameter.permit(:year, :month, :day, :project_id, :time, :summary)
	end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [ :edit, :update, :destroy, :replace ]
	before_action :set_projects, only: [ :index ]

	def index
		@project_id = flash[:project_id]
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)

		# ソート順をデータベース中のorderの最大値+1に設定
		order = Project.maximum(:order)
		if order.nil?
			@project.order = 0
		else
			@project.order = order + 1
		end

		if @project.save
			redirect_to action: :index
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @project.update_attributes(project_params)
			redirect_to action: :index
		else
			render :edit
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_url
	end

	def replace
		tmp_order = @project.order
		replaced_project = Project.find(params[:replaced_id])
		Project.transaction do
			@project.order = replaced_project.order
			@project.save!
			replaced_project.order = tmp_order
			replaced_project.save!
		end
		flash[:project_id] = params[:id]
		redirect_to action: :index
		rescue => e
		render plain: e.message
	end

	def replace_all
		projects = params[:projects]
		Project.transaction do
			order = 0
			projects.each do |id|
				project = Project.find(id)
				project.order = order
				project.save!
				order += 1
			end
		end
		flash[:project_id] = params[:project_id]
		redirect_to action: :index
		rescue => e
		render plain: e.message
	end

	private

		def project_params
			params.require(:project).permit(:name, :period_flag, :begin_date, :end_date, :flag)
		end

		def set_project
			@project = Project.find(params[:id])
		end

		def set_projects
			@projects = Project.all.order(:order)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
	def show
		@user = User.find(params[:id])
		@users = User.all
		
		@date = get_date_param

		@operatings = Operating.select('user_id, year, month, project_id, SUM(time) AS sum_time').group(
			:user_id, :year, :month, :project_id).having(user_id: params[:id], year: @date.year, month: @date.month)

		@total = @operatings.inject(0) {|result, v| result + v.sum_time }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operatings_helper.rb
module OperatingsHelper

	# 日付に対応する曜日クラスを返す
	def class_for_operating_date (date)
		dow_class = ""
		if (date.sunday? || HolidayJp.holiday?(date)) then
			dow_class = "holiday"
		elsif date.saturday?
			dow_class = "saturday"
		end
	end

	# 時刻の出力フォーマットを整える
	def adjust_time time
		adjust_time = "" 
		adjust_time = "%g" % time unless time.nil?
	end

	# 他ユーザーの稼働実績を閲覧できる権限があるならtrue
	def all_operatings_available?
		true
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper

	def button_disabled
		@project_id.blank?
	end

	def button_up_disabled
		return true if @project_id.blank?
		if @projects.length > 0 && @projects[0].id == @project_id.to_i
			true
		else
			false
		end
	end

	def button_down_disabled
		return true if @project_id.blank?
		if @projects.length > 0 && @projects[@projects.length-1].id == @project_id.to_i
			true
		else
			false
		end
	end

	def is_project_checked id
		if @project_id.present? && @project_id.to_i == id
			true
		else
			false
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user = User.find(1)
	end
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/layouts/_header.html.erb
<table style="width:98%">
	<tr>
		<% if yield(:date_selectable).present? then %>
		<td style="text-align: left;" width="40">
			<%= link_to '<<', action: :show,
				year: @date.prev_month.year, month: @date.prev_month.month %>
		</td>
		<% end %>
		<td class="heading"><%= @date.strftime("%Y年%m月") %> <%= yield(:heading) %></td>
		<% if yield(:date_selectable).present? then %>
		<td style="text-align: right;" width="40">
			<%= link_to '>>', action: :show,
				year: @date.next_month.year, month: @date.next_month.month %>
		</td>
		<% end %>
	</tr>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
	<a class="navbar-brand" href="#" id="logo"><%= t 'view.app_name' %></a>
	<ul class="navbar-nav">
 		<li class="nav-item active">
 			<%= link_to t('view.operatings.title'), operating_path(current_user), class: 'nav-link' %></a>
 		</li>
 		<li class="nav-item active"><a class="nav-link" href="/projects">プロジェクト編集</a></li>
 		<li class="nav-item active"><a class="nav-link" href="/sample">ユーザ権限設定</a></li>
	</ul>
</nav>

app/views/layouts/_user.html.erb
<% if all_operatings_available? then %>
	<%= select_tag :users,
		options_from_collection_for_select(@users, :id, :group_and_name, @user.id) %> 
<% else %>
	<%= @user.group_and_name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OperatingManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  	<div class="container">

      <div class="row">
<!--
        <div class="col-sm-2">
          サイドバー

          <ul style="list-style-type: none;font-size: 0.9em;margin-top: 10px; padding-left: 10px;">
          </ul>
        </div>
        <div class="col-sm-10">
//-->
        <div class='col-12'>
          <%= yield %>
        </div>
      </div>

    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/operatings/edit.html.erb
<% provide(:heading, t('view.operatings.title')) %>

<%= render 'layouts/header' %>

<%= form_tag operating_path(@user), method: :patch do %>

<%= hidden_field_tag :year, @date.year %>
<%= hidden_field_tag :month, @date.month %>

<table width="98%" style="font-size: 0.8em;">
	<tr>
		<td><%= @user.group_and_name %></td>
		<td style="text-align: right;">
			<%= button_tag '登録', class: 'btn btn-primary btn-custom' %>
			<%= link_to 'キャンセル', { action: :show, year: @date.year, month: @date.month },
				{ class: 'btn btn-secondary btn-custom', role: :button } %>
		</td>
	</tr>
</table>
<div id="operatings">
<table width="98%">
	<tr>
		<th width="30"></th>
		<th width="45">日付</th>
		<th width="40">曜日</th>
		<th width="220">プロジェクト名</th>
		<th width="55">時間</th>
		<th width="">備考</th>
		<th width="30">消</th>
	</tr>
	<%
		current_month = @date.month
		d = Date.new(@date.year, @date.month, 1)
		i = 0
		while (d.month == current_month) do
			operatings = @operatings.select {|op| [op.year,op.month,op.day] == [d.year,d.month,d.day]}
			operating_count = operatings.length
	%>
	<tr id="row_<%= i %>_0" class="<%= class_for_operating_date d %>">
		<td>
			<div id="add_column_<%= i %>" class="div_btn" data-index="<%= i %>">
				+
				<%= hidden_field_tag "operating[%d][0][year]" % i, d.year %>
				<%= hidden_field_tag "operating[%d][0][month]" % i, d.month %>
				<%= hidden_field_tag "operating[%d][0][day]" % i, d.day %>
				<input type="hidden" name="counter" id="counter_<%= i %>"
				 disabled="disabled" value ="<%= operating_count == 0 ? 1 : operating_count %>">
			</div>
		</td>
		<td class="date"><%= d.strftime("%m/%d") %></td>
		<td class="dow"><%= d.strftime("%a") %></td>
		<td>
			<%= select_tag "operating[%d][0][project_id]" % i, 
				options_from_collection_for_select(@projects, :id, :name, 
					operating_count == 0 ? "" : operatings[0].project_id), 
				include_blank: true %>
		</td>
		<td>
			<%= number_field_tag "operating[%d][0][time]" % i,
				operating_count == 0 ? "" : adjust_time(operatings[0].time), 
				{ min: 0, max: 24, step: 0.25, class: :input_time } %>
		</td>
		<td>
			<%= text_field_tag "operating[%d][0][summary]" % i, 
				operating_count == 0 ? "" : operatings[0].summary,
				{ class: :input_summary, list: :summary_list, autocomplete: :off } %>
		</td>
		<td><button type="button" id="btn_clear_<%= i %>"></button></td>
	</tr>

		<% 
			if operating_count > 1 then
				(1..operating_count-1).each do |j|
		%>

	<tr id="row_<%= i %>_<%= j %>" class="<%= class_for_operating_date d %>">
		<td class="sub_row">
			<div id="rm_column_<%= i %>_<%= j %>" class="div_btn sub_col opened" data-index="<%= i %>_<%= j %>">
				-
				<%= hidden_field_tag "operating[%d][%d][year]" % [i, j], d.year %>
				<%= hidden_field_tag "operating[%d][%d][month]" % [i, j], d.month %>
				<%= hidden_field_tag "operating[%d][%d][day]" % [i, j], d.day %>
			</div>
		</td>
		<td></td>
		<td></td>
		<td>
			<div class="sub_col opened">
				<%= select_tag "operating[%d][%d][project_id]" % [i, j], 
					options_from_collection_for_select(@projects, :id, :name, operatings[j].project_id), 
					include_blank: true %>
			</div>
		</td>
		<td>
			<div class="sub_col opened">
				<%= number_field_tag "operating[%d][%d][time]" % [i, j], 
					adjust_time(operatings[j].time), { min: 0, max: 24, step: 0.25, class: :input_time } %>
			</div>
		</td>
		<td>
			<div class="sub_col opened">
				<%= text_field_tag "operating[%d][%d][summary]" % [i, j], 
					operatings[j].summary, 
					{ class: :input_summary, list: :summary_list, autocomplete: :off } %>
			</div>
		</td>
		<td></td>
	</tr>

	<%
				end
			end
		d += 1
		i += 1
		end
	%>
</table>
</div>

<% end %>

<datalist id="summary_list">
</datalist>

<%= javascript_tag do %>
var projects = [
	<% @projects.each do |p| %>
	{ "id":<%= p.id %>, "name":"<%= p.name %>" },
	<% end %>
];
<% end %>

app/views/operatings/show.html.erb
<% provide(:heading, t('view.operatings.title')) %>
<% provide(:date_selectable, true) %>

<%= form_tag operating_path(@user), method: :get, id: :form_for_user_selectbox do %>
	<%= hidden_field_tag :year, @date.year %>
	<%= hidden_field_tag :month, @date.month %>
<% end %>

<%= form_tag edit_operating_path, method: :get do %>

	<%= hidden_field_tag :year, @date.year %>
	<%= hidden_field_tag :month, @date.month %>


<%= render 'layouts/header' %>
<div style="width: 98%; text-align: right; font-size: 0.8em;">
	<%= link_to '稼働集計表へ', controller: :spreadsheets, action: :show, year: @date.year, month: @date.month %>
</div>
<table width="98%" style="font-size: 0.8em;">
	<tr>
		<td>
			<%= render 'layouts/user' %>
		</td>
		<td style="text-align: right;">
			<%= button_tag '編集', class: 'btn btn-primary btn-custom' %>
		</td>
	</tr>
</table>
<div id="operatings">
<table width="98%">
	<tr>
		<th width="45">日付</th>
		<th width="40">曜日</th>
		<th width="220">プロジェクト名</th>
		<th width="55">時間</th>
		<th width="">備考</th>
	</tr>
	<%
		current_month = @date.month
		d = Date.new(@date.year, @date.month, 1)
		while (d.month == current_month) do
			operatings = @operatings.select {|op| [op.year,op.month,op.day] == [d.year,d.month,d.day]}
			operatings << Operating.new({ year: d.year, month: d.month, day: d.day }) if operatings.empty?
			operatings.each_with_index do |operating, i|
	%>

	<tr id="row_<%= i %>_0" class="<%= class_for_operating_date d %>">
		<td class="date"><%= d.strftime("%m/%d") if i == 0 %></td>
		<td class="dow"><%= d.strftime("%a") if i == 0 %></td>
		<td class="project_name"><%= operating.project.name unless operating.project.nil? %></td>
		<td class="time"><%= adjust_time(operating.time) %></td>
		<td class="summary"><%= operating.summary %></td>
	</tr>

	<%
			end
		d += 1
		end
	%>
</table>
</div>

<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  	<div id="error_explanation">
  		<ul>
  	      <% @project.errors.full_messages.each do |msg| %>
  	    	<li><%= msg %></li>
  	      <% end %>
  		</ul>
  	</div>
  <% end %>
<div id="project_form">
<table>
	<tr>
		<td class="header">プロジェクト名</td>
		<td><%= f.text_field :name %></td>
	</tr>
	<tr>
		<td class="header">期間</td>
		<td style="text-align: left;">
			<%= f.radio_button :period_flag, true %>期間あり
			<%= f.month_field :begin_date %>〜<%= f.month_field :end_date %>
			<%= f.radio_button :period_flag, false %>期間なし
		</td>
	</tr>
	<tr>
		<td class="header">表示設定</td>
		<td style="text-align: left;">
			<%= f.radio_button :flag, true %>表示する
			<%= f.radio_button :flag, false %>表示しない
		</td>
	</tr>
</table>
<div style="width: 98%; text-align: right; padding: 2px;">
	<%= f.submit '登録', class: 'btn btn-primary btn-custom' %>
	<%= link_to 'キャンセル', '#',  { class: 'btn btn-secondary btn-custom', role: :button, onclick: "history.back();" } %>
</div>
</div>
<% end %>

app/views/projects/edit.html.erb
<div class="heading">プロジェクト編集</div>
<%= render 'projects/form' %>

app/views/projects/index.html.erb
<div class="heading">プロジェクト一覧</div>

<div style="text-align: right; width: 98%; font-size: 0.8em; padding: 2px;">
	<%= link_to 'プロジェクトを追加', action: :new %>
</div>

<div style="text-align: left; width: 98%; font-size: 0.8em; padding: 2px;">
<%= form_tag '', method: :delete do %>
	<%= button_tag '編集', { id: :edit, type: :button, class: 'btn btn-primary btn-custom',
							disabled: button_disabled } %>
	<%= button_tag '削除', { id: :delete, type: :submit, class: 'btn btn-primary btn-custom',
							disabled: button_disabled } %>
	<%= button_tag '上へ', { id: :up, type: :button, class: 'btn btn-primary btn-custom',
							disabled: button_up_disabled } %>
	<%= button_tag '下へ', { id: :down, type: :button, class: 'btn btn-primary btn-custom',
							disabled: button_down_disabled } %>
<% end %>
</div>
<%= form_tag projects_replace_all_path, id: :form_projects do %>
<div id="projects">
<table>
<thead>
	<tr>
		<th width=""></th>
		<th>プロジェクト名</th>
		<th width="180">期間</th>
		<th width="120">表示</th>
	</tr>
</thead>
<tbody id="sortable_table">
	<% @projects.each do |project| %>
	<tr>
		<td class="radio_button">
			<%= radio_button_tag :project_id, project.id, is_project_checked(project.id),
				{ data: { path: project_path(project.id) } } %>
			<%= hidden_field_tag 'projects[]', project.id %>
		</td>
		<td class="project_name"><%= project.name %></td>
		<td class="period"><%= project.period %></td>
		<td><%= project.flag ? '○' : '×' %></td>
	</tr>
	<% end %>
</tbody>
</table>
</div>

<%= javascript_tag do %>

jQuery(function($){
	var fixhelper = function(ev, ui) {
		ui.children().each(function() {
			$(this).width($(this).width());
		});
		return ui;
	};
	$('#sortable_table').sortable({ helper: fixhelper,
		update: function(ev, ui) {
			$('#form_projects').submit();
		} 
	});
});

<% end %>

<% end %>

app/views/projects/new.html.erb
<div class="heading">新規プロジェクト入力</div>
<%= render 'projects/form' %>

app/views/spreadsheets/show.html.erb
<% provide(:heading, t('view.spreadsheets.title')) %>
<% provide(:date_selectable, true) %>

<%= form_tag spreadsheet_path(@user), method: :get, id: :form_for_user_selectbox do %>
	<%= hidden_field_tag :year, @date.year %>
	<%= hidden_field_tag :month, @date.month %>
<% end %>

<%= render 'layouts/header' %>
<div style="width: 98%; text-align: right; font-size: 0.8em;">
	<%= link_to '稼働実績表へ', controller: :operatings, action: :show, year: @date.year, month: @date.month %>
</div>
<table width="98%" style="font-size: 0.8em;">
	<tr>
		<td>
			<%= render 'layouts/user' %>
			
			
		</td>
		<td style="text-align: right;">
		</td>
	</tr>
</table>
<div id="spreadsheet">
<table width="98%">
	<thead>
		<tr>
			<th width="220">プロジェクト名</th>
			<th width="55">稼働時間</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td class="total">総計</td>
			<td class="total_time"><%= @total %></td>
		</tr>
	</tfoot>
	<% @operatings.each do |operating| %>
	<tr>
		<td class="project_name"><%= operating.project.name unless operating.project.nil? %></td>
		<td class="time"><%= operating.sum_time %></td>
	</tr>
	<% end %>
</table>
</div>